name: Pre-Commit Auto-Update

# Controls when the action will run.
on:
  schedule:
  # Automatically run on every Sunday
  - cron: 0 0 * * 0
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.6.0
    - name: Install setuptools
      run: |
        sudo apt-get install --reinstall python-pkg-resources
    - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0
    - uses: peter-evans/create-pull-request@v7.0.8
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/pre-commit-hooks
        title: Update pre-commit hooks
        commit-message: 'chore: update pre-commit hooks'
        body: Update versions of pre-commit hooks to latest version.
