name: Pre-Commit Auto-Update

# Controls when the action will run.
on:
  schedule:
  # Automatically run on every Sunday
  - cron: 0 0 * * 0
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    uses: browniebroke/github-actions/.github/workflows/pre-commit-autoupdate.yml@v1
    secrets:
      gh_pat: ${{ secrets.WORKFLOW_SECRET }}
