name: GitHub Actions Version Auto-Update

# Controls when the action will run.
on:
  schedule:
    # Automatically run on every Sunday
  - cron: 0 0 * * 0
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        token: ${{ secrets.WORKFLOW_SECRET }}
    - name: Run GitHub Actions Version Updater
      uses: saadmk11/github-actions-version-updater@v0.8.1
      with:
        token: ${{ secrets.WORKFLOW_SECRET }}
